theme: soho
baseurl: https://example.com/
languageCode: en
title: Soho Theme
DefaultContentLanguage: en
enableInlineShortcodes: yes
summarylength: 10
enableEmoji: yes
paginate: 5
params:
  builtWith: yes
  copyright: Author Name
  description: Example Blog
  images: images/profile.png
  license: CC BY-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0
  mainSections: post
  profilePicture: images/profile.png
  socialIcons:
    - icon: fa-linkedin
      title: Linkedin
      url: '#'
    - icon: fa-github
      title: GitHub
      url: https://github.com/alexandrevicenzi/soho
    - icon: fa-twitter
      title: Twitter
      url: '#'
  title: Soho Theme
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 100
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 200
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 200
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20
markup:
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: no
    lineNumbersInTable: yes
    noClasses: yes
    style: monokai
    tabWidth: 4
